language: java
matrix:
  include:
  - jdk: openjdk8
    env: GRADLE_PUBLISH=true
  - jdk: openjdk11
    env: GRADLE_PUBLISH=false
  - jdk: openjdk13
    env: GRADLE_PUBLISH=false
dist: xenial
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
env:
  global:
  - secure: SMDLZidvlVSx+Fb7GBklScg+FtVahoysKZdLPfX1dtf0meuDIttTS+a2Jbj/+CTMfblq7mmM0YlrW2PElCNAi2I+Gzm0v8ZHZPfVvMkJRaX0TGpb+Pcsx/T2xIwMFMuKUzP1j9ifIKDVYlB9mcIZl+8p8PwIy4tkBX3CwCIZ5XM=
  - secure: M/0m7dlUrOMdc0daFGHqyf3HZWT+2QIYZp4roiHyLQGzuXwX721Wt/Hi3xxchtX85Qulx0BV1h54SrDfIqxwYq38EiamzVR1n0uqoRC/TNo4JgB6oFd8/PLS9pLiUClG6GNOelulNyK6pl0WdL4G1xdvHla0/4wMulygbWmxKPU=
  - secure: Vyc7iLE+lnQJEXD4X7O5PFF3ffeSqAyeQgJ/Gn4pJbZ2A6JtdPIZlHXDtV+mC+ZIgOGQI6vUzCWulc/p21zpphXWrCtCrLVDhP/AtKzyuxBGXZxTaqcApD3MMTvKPOzIjgxNfFEgqmbCx1wAFJy2w1gTR5zy6qcPzanqKtv/epE=
  - secure: G9mNkiKTp9x4ZL/pbZYcmAceFmgQYEhwUz9ZFl2SQ2MCONrhez/bg/GW58ML8LLSP49sLTM7/jQb6+cWfsxntd/uxw19Km0nzgCkEpLJHtk05gVXxTBsAv8V/itgLNheIgTlg1is+Xt17WzlV7L4OIp/LV7SJv/xaTmXdeyeu1E=
cache:
  directories:
  - $HOME/.gradle
