name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'
          cache: 'gradle'
      - run: echo "JDK19=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: 'gradle'
      - run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
      - name: Build candidate
        if: contains(github.ref, '-rc.')
        run: ./gradlew --info --stacktrace -Prelease.useLastTag=true candidate
        env:
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
      - name: Build release
        if: (!contains(github.ref, '-rc.'))
        run: ./gradlew --info -Prelease.useLastTag=true final
        env:
          NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
          NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
